### ISSUE TITLE
List Helm chart on Artifacthub

### ISSUE THREAD

**Issue by brandan-schmitz** [pabloromeo/clusterplex#236]
Adding the helm chart from this repository to [Artifacthub](https://artifacthub.io/) would be a great way to make it more discoverable. It has become kinda a central location for searching for helm charts and other k8s deployment resources.

You would want to add a `artifacthub-repo.yml` file to the gh-pages branch before adding the repo on Artifacthub. This will allow it to show on their site as the verified publisher. The email address needs to match the one used for the account on ArtifactHub.
https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-repo.yml

```yaml
repositoryID: clusterplex
owners:
  - name: pabloromeo
    email: user1@email.com
```
