### ISSUE TITLE
Verbose logging

### ISSUE THREAD

**Issue by christianmerges** [pabloromeo/clusterplex#248]
**Describe the bug**
When i deploy in docker swarm with docker mods, the movie doesn't start, but in the dashboard section of plex, the time of the movie is already running. How can i debug this?

**yaml**
```
version: '3.8'
services:
  plex:
    image: ghcr.io/linuxserver/plex
    environment:
      DOCKER_MODS: "ghcr.io/pabloromeo/clusterplex_dockermod:latest"
      VERSION: docker
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      ORCHESTRATOR_URL: http://plex-orchestrator:3500
      PMS_SERVICE: plex     # This service. If you disable Local Relay then you must use PMS_IP instead
      PMS_PORT: "32400"
      TRANSCODE_OPERATING_MODE: remote #(local|remote|both)
      TRANSCODER_VERBOSE: "1"   # 1=verbose, 0=silent
      LOCAL_RELAY_ENABLED: "1"
      LOCAL_RELAY_PORT: "32499"
    volumes:
      - /mnt/docker/plex/config:/config
      - /mnt/transcode:/transcode  #glusterfs volume on both docker hosts
      - /mnt/merge/:/cloud	   #media folder
      - /etc/localtime:/etc/localtime:ro
      - /mnt/docker/plex/tmp:/tmp	#ramdisk too small when generating thumbnails etc. for new media
    networks:
      - pirate
    deploy:
      placement:
        constraints: [node.labels.type == cpu]
      mode: replicated
      replicas: 1


  plex-orchestrator:
    image: ghcr.io/pabloromeo/clusterplex_orchestrator:latest
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
      placement:
        constraints: [node.labels.type == cpu]
    healthcheck:
      test: curl -fsS http://localhost:3500/health > /dev/null || exit 1
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 30s
    environment:
      TZ: Europe/Berlin
      LISTENING_PORT: 3500
      WORKER_SELECTION_STRATEGY: "LOAD_RANK" # RR | LOAD_CPU | LOAD_TASKS | LOAD_RANK (default)
    volumes:
      - /etc/localtime:/etc/localtime:ro

  plex-worker:
    image: ghcr.io/linuxserver/plex:latest
    hostname: "plex-worker-{{.Node.Hostname}}"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.type == gpu]
    environment:
      DOCKER_MODS: "ghcr.io/pabloromeo/clusterplex_worker_dockermod:latest"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
      VERSION: docker
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
      LISTENING_PORT: 3501      # used by the healthcheck
      STAT_CPU_INTERVAL: 2000   # interval for reporting worker load metrics
      ORCHESTRATOR_URL: http://plex-orchestrator:3500
      EAE_SUPPORT: "1"
      FFMPEG_HWACCEL: "true"
    healthcheck:
      test: curl -fsS http://localhost:3501/health > /dev/null || exit 1
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 240s
    volumes:
      - /mnt/transcode:/transcode        #glusterfs volume
      - /mnt/merge:/cloud                   #media folder

networks:
  pirate:
    driver: overlay
    driver_opts:
      com.docker.network.driver.mtu: 1200
````

**Expected behavior**
the worker should transcode

**Server (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS

**Additional context**
I can see that there is a sub-folder created in the /transcode directory, but there are no files inside.
