### ISSUE TITLE
Hardware Acceleration for Transcoding in Docker Swarm Intel-Quicksync

### ISSUE THREAD

**Issue by Nullvoid3771** [pabloromeo/clusterplex#336]
### Intel QuickSync HW Transcoding Guide for Docker Swarm

**Stop!: Important** 

This guide walks you through enabling Intel QuickSync Hardware (HW) Transcoding in Docker Swarm, with a focus on setting up the necessary configurations across all Swarm nodes. **Important**: You must customize the Docker image search commands to use the correct image names, particularly with grep ghcr.io/linuxserver/plex:latest. 
example part of script:

```
dminor=$((0x${minor}))
dmajor=$((0x${major}))
CID=`docker ps -a --no-trunc | grep plexinc/pms-docker:latest | head -1 |  awk '{print $1}'`
if [[ -z $CID ]]; then
    echo 'CID not found'
    exit
fi
```

Change to on PMS & Worker host machines: 
```
CID=`docker ps -a --no-trunc | grep ghcr.io/linuxserver/plex:latest | head -1 |  awk '{print $1}'`

```

### Link to guide:

https://www.linkedin.com/pulse/docker-swarm-reducing-plex-cpu-utilisation-60-reis-holmes

### Disclaimer:

This guide is provided without support. I take no responsibility for any configuration issues or damage to your systems. If you encounter issues, you may need to troubleshoot further. Credit goes to the original author in the link above, I only modified the configuration for use in Clusterplex.

Prerequisites

	•	Apply these steps on each node in your Docker Swarm cluster.
	•	Ensure your system supports Intel QuickSync.
	•	Plex Pass is required for PMS hardware transcoding.
	•	Ensure firewall settings allow the necessary ports.
	•	If you encounter errors, consult an expert or search online for solutions.

Note: Proxmox users might face challenges due to its headless nature. Further troubleshooting may be required. See “For Proxmox Users” below for more details. For this reason I was unable to get HW Transcoding working myself, however what I’ve learned might help others. I might revisit this project in the future, but for now software transcoding works. 

=============

### **Below this point everything is for troubleshooting:**

=============

Further hints to make HW Transcoding work might be found here: https://github.com/pabloromeo/clusterplex/issues/223

Environment Configuration

Well not necessary to optimize your setup, if you consider adding the following environment variables to your PMS and Worker Docker container configurations:

```
deploy:
      resources:
        reservations:
          generic_resources:
            - discrete_resource_spec:
                kind: 'gpu'
                value: 1
```

Warning: This configuration might cause an error like no suitable node (insufficient resources on 2 nodes). If this happens, remove the line or use `docker node inspect <node>` to check resource availability.

FFMPEG HW Acceleration Options

You can set the hardware acceleration environment variable to one of the following options:

environment:
 ` FFMPEG_HWACCEL: vaapi | qsv | drm | opencl`

Volume Mapping for Hardware Transcoding

Ensure you map the necessary device volumes for hardware transcoding within the container:

Additional Media mapping might be found here: https://github.com/pabloromeo/clusterplex/issues/335

```
volumes:
  - /dev/dri:/dev/dri
  - type: bind
    source: /mnt/pve/cephfs/plexconf/Library/Application Support/Plex Media Server/Drivers/
    target: /Drivers
```

Note: Verify the paths carefully. If incorrect, you may end up in the wrong directory. Adjust mappings as needed based on your Ceph configuration.

Additional Mappings (Optional)

```
volumes:
  - /dev/dri/renderD128:/dev/dri/renderD128
  - /dev/dri/card0:/dev/dri/card0
```

Well `devices:` may not be necessary this would be the configuration *with optional mappings.  

```
devices:
  - /dev/dri/renderD128:/dev/dri/renderD128
  - /dev/dri/card0:/dev/dri/card0
  - /dev/dri/:/dev/dri/
```

Expected Output

If successful, your output should look like this:

```
**** creating video group videoh241 with id 104 ****
**** adding /dev/dri/renderD128 to video group videoh241 with id 104 ****
**** adding /dev/dri/card0 to video group video with id 44 ****
```

**Troubleshooting Potential Plex Worker Errors**

You may encounter the following errors:

	1.	Hardware transcoding device error:
`
[Req#6018/Transcode] Codecs: hardware transcoding: opening hw device failed - probably not supported by this system, error: Invalid argument
`

	2.	HEVC decoder issue:
```

[Req#86b9/Transcode] Codecs: testing hevc (decoder) with hwdevice vaapi
[AVHWDeviceContext @ 0x7e9bfbd60d40] Failed to get number of OpenCL platforms: -1001.
Device creation failed: -19.
[hevc @ 0x7e9bfb060b80] No device available for decoder: device type opencl needed for codec hevc.
```
These errors could indicate that your iGPU doesn’t support HEVC or the required HW acceleration methods or their is a configuration issue somewhere in your setup. 

**Compatibility Issues**

```
Much older Intel iGPUs may not support vaapi or vainfo. Pre-broadwell CPU’s should use i965 as it support Vaapi, but not QSV. You may need to set the following environment variable in /etc/environment

LIBVA_DRIVER_NAME=`iHD` or `i965`

Additional information can be found here: 

https://wiki.archlinux.org/title/Hardware_video_acceleration

https://wiki.debian.org/HardwareVideoAcceleration

```

**GPU Information and Installation of Vainfo**

To check your GPU details:

`sudo vainfo`

To install the necessary packages:

```
sudo apt install

vainfo
libva2
libva-drm2
libva-x11-2
intel-media-va-driver-non-free               #apt-add-repository -y -c non-free
intel-media-va-driver
i965-va-driver
intel-gpu-tools
intel-opencl-icd
libdrm-intel1
mesa-utils
```

Example of vainfo: 

```
libva info: VA-API version 1.17.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_17
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.17 (libva 2.12.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 23.1.1 ()
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
```

###Caution!: 
**PMS & Workers will likely expect under /Drivers within your docker containers; i965_drv_video.so if i965 or iHD_drv_video.so if iHD, however if you have a mix of older and newer CPU’s you may cause a conflict.** (Honestly I’m not sure if this would cause issues or require you to copy extra drivers needed to /Drivers.)

To check if your iGPU is rendering:

`intel_gpu_top`

**Modifying Docker Daemon**

You may need to modify the daemon.json file on each node:

/etc/docker/daemon.json

```
{
  "default-runtime": "runc",
  "runtimes": {
    "runc": {
      "path": "/usr/bin/runc"
    }
  }
}
```

Reboot your systems after saving the file. However, note that this method might crash Docker. You can check your default runtime with `docker info`.

**For Proxmox Users**

You might achieve better results by setting up your Docker Swarm on two or more Ubuntu VMs, connecting to Ceph storage located on your bare-metal Proxmox clusters.

```
1. CephFS (Ceph File System) Client

CephFS allows you to mount a Ceph-backed file system on your Linux machine.

Prerequisites:

	•	The ceph-common package is required to install the necessary tools for interacting with the Ceph cluster.

Steps:

	1.	Install Ceph Tools on the Client Machine

sudo apt-get install ceph-common

On RHEL/CentOS:

sudo yum install ceph-common


	2.	Get the Ceph Configuration and Authentication Files
You will need the Ceph configuration file (ceph.conf) and a client authentication keyring (usually client.admin.keyring) to authenticate with the cluster. These files should be provided by the Ceph administrator.
	3.	Mount the CephFS
Use the following command to mount the CephFS:

sudo mount -t ceph <mon_host1>,<mon_host2>,<mon_host3>:<path> /mnt/cephfs -o name=<client_name>,secret=<key>,noatime

For example:

sudo mount -t ceph mon1.example.com:/ /mnt/cephfs -o name=admin,secret=AQC5mXVZAAAABFAAtFrH6Z4KoWoJlQq+MeBArA==

Alternatively, if you have the ceph.conf and keyring file:

sudo mount -t ceph mon1.example.com:/ /mnt/cephfs -o name=client.admin,secretfile=/etc/ceph/ceph.client.admin.keyring


	4.	Unmount CephFS
When you’re done using the Ceph file system, you can unmount it:

sudo umount /mnt/cephfs
```
**Error and fix for EAE watchfolder is not writable:**

The fix for this is to create multiple tmp folders in ceph. Then create multiple workers with different names. constrict each worker and PMS to a single replica and locked to specific nodes. Make sure your tmp folders have write permissions. Adapt to your environment and add appropriate volume mappings. You don't even need to do this in ceph you can do it in local volumes, because you’re constraining your containers to a specific node. This sounds counter intuitive since you’re either using K8 or swarm, but it's what I found worked. If you share tmp folders you will run into conflicts.

```

Docker Swarm Stack - Sry I don’t use K8

services:
 plex:
   image: ghcr.io/linuxserver/plex:latest
   deploy:
     placement:
       constraints:
         - node.hostname == node1
     mode: replicated
     replicas: 1

volumes: 
- type: bind             
        source: $HOST/mnt/pve/cephfs/tmp
        target: /tmp 


plex-worker:
   image: ghcr.io/linuxserver/plex:latest
   hostname: "plex-worker-{{.Node.Hostname}}"
   deploy:
     placement:
       constraints:
         - node.hostname == node2
     mode: replicated
     replicas: 1

volumes: 
- type: bind             
        source: $HOST/mnt/pve/cephfs/tmp2
        target: /tmp 


plex-worker2:
   image: ghcr.io/linuxserver/plex:latest
   hostname: "plex-worker2-{{.Node.Hostname}}"
   deploy:
     placement:
       constraints:
         - node.hostname == node3
     mode: replicated
     replicas: 1

volumes: 
- type: bind             
        source: $HOST/mnt/pve/cephfs/tmp3
        target: /tmp 

```

Example Docker Swarm Stack Configuration *Does not include EAE watchfolder not writable fix as it maybe user related. 
```

version: '3.8'

services:
  plex:
    image: ghcr.io/linuxserver/plex:latest
    deploy:
      placement:
        constraints:
          - node.hostname == pve  #replace with node name if you want to constrict PMS to one node. 
      mode: replicated
      replicas: 1
    environment:
      DOCKER_MODS: "ghcr.io/pabloromeo/clusterplex_dockermod:latest"
      VERSION: docker
      PUID: 1000
      PGID: 1000
      TZ: America/Toronto
      ORCHESTRATOR_URL: http://plex-orchestrator:3500
      PMS_SERVICE: plex  # This service. If you disable Local Relay then you must use PMS_IP instead
      PMS_PORT: "32400"
      TRANSCODE_OPERATING_MODE: both #(local|remote|both)         #Works only in local PMS mode. 
      TRANSCODER_VERBOSE: "1"   # 1=verbose, 0=silent
      LOCAL_RELAY_ENABLED: "1"
      LOCAL_RELAY_PORT: "32499"
      FORCE_HTTPS: "0"
      FFMPEG_HWACCEL: vaapi
      XDG_RUNTIME_DIR: /run/user/0 #change the UID to your host systems user.
    healthcheck:
      test: curl -fsS http://localhost:32400/identity > /dev/null || exit 1
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 30s
    volumes:
       - type: bind                       
         source: $HOST/mnt/pve/cephfs/plexconf/
         target: /config
       - type: bind               
         source: $HOST/mnt/pve/Movies
         target: /data/movies
       - type: bind
         source: $HOST/mnt/pve/TvShows
         target: /data/tvshows
       - type: bind             
         source: $HOST/mnt/pve/cephfs/plexconf/Library/Application Support/Plex Media Server/Cache/
         target: /transcode 
       - type: bind             
         source: $HOST/mnt/pve/cephfs/data/pms
         target: /data
       - /dev/dri/:/dev/dri/
    
       
    ports:        #All ports in proxmox, and vms have been allowed including 3501 which was not stated, but since it listens. 
      - 32499:32499     # LOCAL_RELAY_PORT
      - 32400:32400
      - 3005:3005
      - 8324:8324
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp

  plex-orchestrator:
    image: ghcr.io/pabloromeo/clusterplex_orchestrator:latest
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
    healthcheck:
      test: curl -fsS http://localhost:3500/health > /dev/null || exit 1
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 30s
    environment:
      TZ: America/Toronto
      LISTENING_PORT: 3500
      WORKER_SELECTION_STRATEGY: "LOAD_RANK" # RR | LOAD_CPU | LOAD_TASKS | LOAD_RANK (default)
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3500:3500

  plex-worker:
    image: ghcr.io/linuxserver/plex:latest
    hostname: "plex-worker-{{.Node.Hostname}}"
    deploy:
      mode: replicated
      replicas: 2
    environment:
      DOCKER_MODS: "ghcr.io/pabloromeo/clusterplex_worker_dockermod:latest"
      VERSION: docker
      PUID: 1000
      PGID: 1000
      TZ: America/Toronto
      LISTENING_PORT: 3501      # used by the healthcheck
      STAT_CPU_INTERVAL: 2000   # interval for reporting worker load metrics
      ORCHESTRATOR_URL: http://plex-orchestrator:3500
      EAE_SUPPORT: "1"
      FFMPEG_HWACCEL: vaapi
      XDG_RUNTIME_DIR: /run/user/0 #change the UID to your host systems user.
    healthcheck:
      test: curl -fsS http://localhost:3501/health > /dev/null || exit 1
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 240s
    volumes: 
       - type: bind 
         source: $HOST/mnt/pve/Movies
         target: /data/movies
       - type: bind                              
         source: $HOST/mnt/pve/TvShows
         target: /data/tvshows
       - type: bind
         source: $HOST/mnt/pve/cephfs/codecs
         target: /codecs
       - type: bind             
         source: $HOST/mnt/pve/cephfs/plexconf/Library/Application Support/Plex Media Server/Cache/
         target: /transcode 
       - type: bind             
         source: $HOST/mnt/pve/cephfs/plexconfworkers
         target: /config
       - type: bind             
         source: $HOST/mnt/pve/cephfs/data/workers
         target: /data
       - type: bind             
         source: $HOST/mnt/pve/cephfs/plexconf/Library/Application Support/Plex Media Server/Drivers/ #This has to be shared between PMS & Workers
         target: /Drivers 
       - /dev/dri/:/dev/dri/
```

This guide should help you set up Intel QuickSync HW Transcoding in your Docker Swarm. Adjust paths and configurations as necessary for your specific environment.
