### ISSUE TITLE
Transcode not working ? no logs on any node/container

### ISSUE THREAD

**Issue by ednxzu** [pabloromeo/clusterplex#78]
setting up the cluster, everything goes according to plan apparently, I'm using the example config with the custom containers (not the docker mods, tho the mods one have had the same behaviour). the server installs correctly, and I'm seeing : 

Worker connected on socket EBKSwQ_lpPPHxRJ5AAAB
Worker connected on socket jzfODhEilMwaWJ7xAAAD
Worker connected on socket het-G-oC57htxvFcAAAF
Worker connected on socket hXDeGp3sXBW5hBHLAAAH
 on the workers side

ON_DEATH: debug mode enabled for pid [1]
Initializing orchestrator
Using Worker Selection Strategy: LOAD_RANK
Stream-Splitting: DISABLED
Setting up websockets
Ready
Server listening on port 3500
Client connected: EBKSwQ_lpPPHxRJ5AAAB
Registering worker 3062a4c0-a201-4887-8fa3-de6905787c2b|plex-worker-ubuntu04
Registered new worker: 3062a4c0-a201-4887-8fa3-de6905787c2b|plex-worker-ubuntu04
Client connected: jzfODhEilMwaWJ7xAAAD
Registering worker f96419bd-dcb6-40ed-87bd-8ed1000b0bd1|plex-worker-ubuntu02
Registered new worker: f96419bd-dcb6-40ed-87bd-8ed1000b0bd1|plex-worker-ubuntu02
Client connected: het-G-oC57htxvFcAAAF
Registering worker e2d7ee0f-8a32-438d-a0d0-85a4ae95e539|plex-worker-ubuntu01
Registered new worker: e2d7ee0f-8a32-438d-a0d0-85a4ae95e539|plex-worker-ubuntu01
Client connected: hXDeGp3sXBW5hBHLAAAH
Registering worker 4215fa59-563d-4131-b6c2-87d5fffd5142|plex-worker-ubuntu03
Registered new worker: 4215fa59-563d-4131-b6c2-87d5fffd5142|plex-worker-ubuntu03
on the orchestrator side

[cont-init.d] 60-plex-update: executing... 
Docker is used for versioning skip update check
[cont-init.d] 60-plex-update: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting Plex Media Server.
[services.d] done.
Critical: libusb_init failed
on the server side

but past that no logs whatsoever, trying to play any content results in a playback error as follow:
Error code: s100X (Network)

I think none of the containers are actually talking tho the metrics are showing up just fine. The really weird thing is that there are no logs anywhere.
docker service logs -f --raw plex_plex-{anything} register logs until everything is started then nothing at all.

I'm running a 4 node cluster in Ubuntu 20.04 VMs freshly installed and on a totally normal network.

Thanks in advance for any help you might get me.

**Comment by pabloromeo** [comment]
In case you find it useful, my current working config is very similar to the one I posted in this other issue:
https://github.com/pabloromeo/clusterplex/issues/71

**Comment by ednxzu** [comment]
Hello, 
Yes I'm using swarm to test this, here is my stack file : 
```
version: '3.9'

services:
  plex:
    image: ghcr.io/linuxserver/plex:latest
    deploy:
      mode: replicated
      replicas: 1
#    labels:
#        - "traefik.enable=true"
#        - "traefik.http.routers.plex.entrypoints=https"
#        - "traefik.http.routers.plex.tls=true"
#        - "traefik.http.routers.plex.rule=Host(`plextest.ednz.fr`)"
#        - "traefik.http.services.plex.loadbalancer.server.port=32400"
    environment:
      DOCKER_MODS: "ghcr.io/pabloromeo/clusterplex_dockermod:latest"
      VERSION: docker
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      ORCHESTRATOR_URL: http://plex-orchestrator:3500
      PMS_IP: 192.168.1.XXX
      TRANSCODE_OPERATING_MODE: both #(local|remote|both)
      TRANSCODER_VERBOSE: "1"   # 1=verbose, 0=silent
    healthcheck:
      test: curl -fsS http://localhost:32400/identity > /dev/null || exit 1
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 30s
    volumes:
      - ./config:/config
      - ./backups:/backups
      - ./tv:/data/tv
      - ./movies:/data/movies
      - ./transcode:/transcode
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 32469:32469
      - 32400:32400
      - 3005:3005
      - 8324:8324
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    networks:
      - traefik-public
      - internal

  plex-orchestrator:
    image: ghcr.io/pabloromeo/clusterplex_orchestrator:latest
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
    environment:
      TZ: Europe/London
      STREAM_SPLITTING: "OFF" # ON | OFF (default)
      LISTENING_PORT: 3500
      WORKER_SELECTION_STRATEGY: "LOAD_CPU" # RR | LOAD_CPU | LOAD_TASKS | LOAD_RANK (default)
    healthcheck:
      test: curl -fsS http://localhost:3500/health > /dev/null || exit 1
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 30s
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3500:3500
    networks:
      - internal


  plex-worker:
    image: ghcr.io/linuxserver/plex:latest
    hostname: "plex-worker-{{.Node.Hostname}}"
    deploy:
      mode: global
      update_config:
        order: start-first
    environment:
      DOCKER_MODS: "ghcr.io/pabloromeo/clusterplex_worker_dockermod:latest"
      VERSION: docker
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      LISTENING_PORT: 3501      # used by the healthcheck
      STAT_CPU_INTERVAL: 2000   # interval for reporting worker load metrics
      ORCHESTRATOR_URL: http://plex-orchestrator:3500
    healthcheck:
      test: curl -fsS http://localhost:3501/health > /dev/null || exit 1
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 240s
    volumes:
      - ./codecs:/codecs # (optional, can be used to share codecs)
      - ./tv:/data/tv
      - ./movies:/data/movies
      - ./transcode:/transcode
      - /etc/localtime:/etc/localtime:ro
    networks:
      - internal

networks:
  internal:
    driver: overlay
  traefik-public:
    external: true
```
The only thing I seems to have done differently is I setup my transcode temp dir to `/transcode` instead of `/tmp/transcode`. Would this explain the problem ?
My local transcode doesn't work either tho, setting up `TRANSCODE_OPERATING_MODE` to both has the exact same behaviour, where it just gives me a network error when trying to transcode.

Thanks for your help !!! I love this project and wanna learn more about it.

**Comment by pabloromeo** [comment]
I would mount /tmp from both Plex and the workers to the same shared location. Just to be safe, and configure it in the Transcode section of Plex.
Now, all those volumes you are mounting, such as tv and movies are network shares, correct?

Also, you can temporarily enable more verbose logging in plex, and view Plex's log in it's own Console within the UI. You should be seeing errors in there which could be more explicit.

PUID and PGID are indeed correct for you, right? Meaning, id 1000 does have access to all those mounts, write access, etc.

One thing to mention: Technically, the only change the dockermod makes is to rename Plex's transcoder, and put a shim in it's place, which attempts to contact the orchestrator, and if it can't, it falls back to Plex's local transcode. So ultimately it should always be able to play back content, it just might not do it using the remote transcoder if it isn't available.
That's why I was wondering if it wasn't a Plex configuration error.

One thing we can test, is to comment out the dockermod, and leave the rest as is. Plex should work, just with the local transcode, as it's basically the a barebones Plex without any changes to it. Once we get that one working, we can enable the dockermod.

**Comment by ednxzu** [comment]
Hello, I indeed mounted both the workers and plex `/tmp` folder into the shared `./transcode` folder. The volumes are CIFS mount points for now as I'm testing. mounted with uid=1000,gid=1000 file and folder mode 777 for debugging, so that everything should be accesible.
I am indeed getting weird messages from the plex console : 
`NetworkServiceBrowser: Error sending out discover packet from 10.0.0.9 to 10.0.0.255: Operation not permitted`
which is a warning and 
`[Transcode] MDE: video has neither a video stream nor an audio stream
[Transcode] Streaming Resource: Cannot make a decision because either the file is unplayable or the client provided bad data
[Transcode] MDE: video has neither a video stream nor an audio stream
`
which is an error, tho the file is perfectly fine (plays just fine on a regular plex)

I am not however, getting any transcode even locally with the dockermod added.
I'm not getting anything without it either so I'm guessing I missed smthg on the plex side regarding networking...

**Comment by ednxzu** [comment]
After a good amount of testing (sorry I'm pretty new to swarm...) I noted that everytime I try to play a media, it shows up as a request from 10.0.0.2 which is the endpoint on the ingress network for swarm, instead of the actual client IP. Idk if it is of any importance but I just found out.

**Comment by pabloromeo** [comment]
I think the NetworkServiceBrowser error can be ignored, I believe that's just autodiscovery stuff, which probably won't work with broadcasts in a docker overlay network. Regarding the 10.0.0.2, that should be fine, swarm will assign internal IPs to each container, and not actual IPs from your LAN.

I still have the impression that Plex itself might be having some issues. Try commenting out the dockermod and recreating the container. Technically it IS just a standard Plex at that point, and i'm pretty sure playback won't work either. Could the network mounts be getting disconnected or become stale?

Lets do it in steps, first get Plex up and running within Swarm with the proper media libraries from CIFS mounts and seeing if it can play back the content, and then we can enable clusterplex on top once we know all that works :)
So let's comment out the dockermod, as well as clusterplex's env vars (ORCHESTRATOR_URL, PMS_IP, TRANSCODE_OPERATING_MODE, TRANSCODER_VERBOSE) and see if Plex works correctly. That makes it a 100% standard Plex instance.

FYI, CIFS mounts for the /config (where application and metadata resides) may cause some problems with Plex's use of its SQLite DB (due to file locking) and Metadata content in plex may also have some issues where it uses symlinks, if I recall correctly. I haven't run it on CIFS in a really long time, but if I remember correctly it could cause issues.
I've moved over to GlusterFS a while ago, but just thought i'd mention it. Media Libraries should be fine over CIFS, NFS, or any other though, as long as it's guaranteed to be mounted and doesn't become stale.

**Comment by ednxzu** [comment]
Hello, 
I figured it out. Basically everything was working fine except that for some reason CIFS mount points don't play nice with either plex or docker as a whole. remounting via NFS fixed everything. In my "production" env it'll be CephFS anyways so it should work just fine. Thanks for helping me out !

**Comment by ednxzu** [comment]
Ok so nevermind haha, remote transcoding seems to not be working. workers don't seems to be able to download codecs on startup (`plex.tv/codecs//linux...` returns 404, tho I think there is a typo because there are 2 / in each url in the logs so idk if that's normal or not.). 

example : 
```
Processing codec libzlib_decoder...
Codec libzlib_decoder.so does not exist. Downloading...
--2021-09-29 09:17:18--  https://downloads.plex.tv/codecs//linux-x86_64-standard/libzlib_decoder.so
Resolving downloads.plex.tv (downloads.plex.tv)... 104.18.13.47, 104.18.12.47, 2606:4700::6812:c2f, ...
Connecting to downloads.plex.tv (downloads.plex.tv)|104.18.13.47|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-09-29 09:17:18 ERROR 404: Not Found.
```

here is orchestrator log from a transcode request
```
Forwarding work request to b30a8d6a-bf5f-475e-9016-eb3665246930|plex-worker-lxdcluster02
Received update for task 576b5121-7a5c-49c4-a3d1-8a051f991868, status: received
Received update for task 576b5121-7a5c-49c4-a3d1-8a051f991868, status: inprogress
Received update for task 576b5121-7a5c-49c4-a3d1-8a051f991868, status: done
Task 576b5121-7a5c-49c4-a3d1-8a051f991868 complete, result: false
Task 576b5121-7a5c-49c4-a3d1-8a051f991868 complete
Job f9ba0067-9049-48e6-a846-7ebf470a1bc6 complete, tasks: 1, result: false
```

**Comment by ednxzu** [comment]
so after some investigation, it seems the `start.sh` script isn't pulling the right infos here are the logs executing it : 
```
root@plex-worker-lxdcluster01:/app# ./start.sh 
./start.sh: line 5: strings: command not found
./start.sh: line 6: strings: command not found
./start.sh: line 7: strings: command not found
CLUSTERPLEX_PLEX_VERSION => ''
CLUSTERPLEX_PLEX_CODECS_VERSION => ''
CLUSTERPLEX_PLEX_EAE_VERSION => 'eae--42'
PLEX_ARCH => 'amd64'
CLUSTERPLEX_PLEX_CODEC_ARCH => linux-x86_64-standard
Codec location => /codecs/-linux-x86_64-standard
Processing codec libaac_decoder...
Codec libaac_decoder.so does not exist. Downloading...
--2021-09-29 10:04:31--  https://downloads.plex.tv/codecs//linux-x86_64-standard/libaac_decoder.so
Resolving downloads.plex.tv (downloads.plex.tv)... 104.18.13.47, 104.18.12.47, 2606:4700::6812:d2f, ...
Connecting to downloads.plex.tv (downloads.plex.tv)|104.18.13.47|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-09-29 10:04:32 ERROR 404: Not Found.
```

**Comment by pabloromeo** [comment]
Ah, it says there that the command "strings" is not installed, which is required in order to extract the version number and codec versions from the plex media server executable.
You are running it right now using the dockermod right?
Do you have the logs of when a worker container starts up? because it should be installing binutils as soon as the dockermod is initialized.

**Comment by ednxzu** [comment]
I am indeed running with the dockermod.
I'll restart the stack to get you the logs 1 sec, Hopefully we're almost live chatting even tho I think you're on the other side of the world !

**Comment by ednxzu** [comment]
```Reading package lists...
W: GPG error: http://archive.ubuntu.com/ubuntu focal InRelease: At least one invalid signature was encountered.
E: The repository 'http://archive.ubuntu.com/ubuntu focal InRelease' is not signed.
W: GPG error: http://archive.ubuntu.com/ubuntu focal-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://archive.ubuntu.com/ubuntu focal-updates InRelease' is not signed.
W: GPG error: http://archive.ubuntu.com/ubuntu focal-security InRelease: At least one invalid signature was encountered.
E: The repository 'http://archive.ubuntu.com/ubuntu focal-security InRelease' is not signed.
**** install binutils, libatomic1, file ****
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package binutils
E: Unable to locate package libatomic1
E: Unable to locate package file
**** install 'n' ****
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 46963  100 46963    0     0   804k      0 --:--:-- --:--:-- --:--:--  804k
**** install nodejs ****
  installing : node-v14.18.0```
I must've missed that, but it actually doesnt find the packages on startup

**Comment by pabloromeo** [comment]
Yeah, I'm in South America :)

Mmmm, that's weird. Do you similar entries when the PMS dockermod initializes? That one installs a few packages as well and it should be running on the same docker image.

Now, one quick thing to test just to get it out of the way. The /tmp share that you mount on both, any chance you could set permissions on that to 777? That startup code of linuxserver's containers doesn't run as the 1000 user, it runs as its internal root prior to switching users. Maybe apt is getting permission denied errors writing to /tmp during the installs.

**Comment by ednxzu** [comment]
```
**** apt-get update ****
Get:1 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Err:1 http://archive.ubuntu.com/ubuntu focal InRelease
  At least one invalid signature was encountered.
Err:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease
  At least one invalid signature was encountered.
Err:3 http://archive.ubuntu.com/ubuntu focal-security InRelease
  At least one invalid signature was encountered.
Reading package lists...
W: GPG error: http://archive.ubuntu.com/ubuntu focal InRelease: At least one invalid signature was encountered.
E: The repository 'http://archive.ubuntu.com/ubuntu focal InRelease' is not signed.
W: GPG error: http://archive.ubuntu.com/ubuntu focal-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://archive.ubuntu.com/ubuntu focal-updates InRelease' is not signed.
W: GPG error: http://archive.ubuntu.com/ubuntu focal-security InRelease: At least one invalid signature was encountered.
E: The repository 'http://archive.ubuntu.com/ubuntu focal-security InRelease' is not signed.
**** install libatomic1, file ****
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libatomic1
E: Unable to locate package file
```
here are the logs from pms starting and apt installing with the pms dockermod

**Comment by ednxzu** [comment]
the whole nfs mount is 777 for debugging for now

**Comment by pabloromeo** [comment]
Yeah, so both fail for the same reason, installing dependencies.
Ah, that's weird, so, are you running the latest docker version? (I'm on 20.10.8 at the moment)
I believe in the past, on older versions there were some problems around an outdated seccomp library.

**Comment by ednxzu** [comment]
Nodes are on version 20.10.7. I'll keep investigating

**Comment by pabloromeo** [comment]
I'll do the same.
In the meantime, one quick test to see if the /tmp mount is causing issues is just to comment out that mount and seeing if it can install dependencies from apt, during startup.

**Comment by pabloromeo** [comment]
Yeah, that doesn't sound ideal at all. Most of what I'm reading seems to point to that old issue around libseccomp.
Maybe something like method 2 mentioned here could work:
https://itectec.com/ubuntu/ubuntu-apt-update-throws-signature-error-in-ubuntu-20-04-container-on-arm/

**Comment by ednxzu** [comment]
Well before I do anything and as the hosts I ran my swarm on were used for a lot of testing, I'm going to reinstall them from scratch with a clean swarm install and all so I can validate that up to that point it all work. Then if the problem persists I'll keep investigating it.

**Comment by pabloromeo** [comment]
Sounds good, let me know if there's anything i can do to help. I'll leave the issue open until we identify a viable workaround that doesn't compromise security.

**Comment by ednxzu** [comment]
Well, new swarm and latest package version later I'm still getting the issue..
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libseccomp2 is already the newest version (2.5.2-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by ednxzu** [comment]
So in the end I got it to work using the custom containers instead of the mods. Now all I have to figure out is why the remote transcode seems to handle the transcoding just fine but nothing happens

**Comment by ednxzu** [comment]
```
[dash @ 0x7f15af98d040] Representation 1 media segment 93 written to: chunk-stream1-00092.m4s
[dash @ 0x7f15af98d040] Opening 'http://192.168.1.110:32400/video/:/transcode/session/uku8o1pwnmrfa0379bw7po4e/d9eaafb7-7ea8-41bf-9d8a-11c992de5de8/manifest?X-Plex-Http-Pipeline=infinite' for writing
[tcp @ 0x7f15af9849c0] Starting connection attempt to 192.168.1.110 port 32400
[tcp @ 0x7f15af9849c0] Successfully connected to 192.168.1.110 port 32400
[AVIOContext @ 0x7f159faace40] Statistics: 0 seeks, 1 writeouts
[dash @ 0x7f15af98d040] Opening 'chunk-stream0-00093.m4s.tmp' for writing
[dash @ 0x7f15af98d040] Opening 'chunk-stream1-00093.m4s.tmp' for writing
[AVIOContext @ 0x7f159faacbc0] Statistics: 0 seeks, 8 writeouts
[dash @ 0x7f15af98d040] Representation 0 media segment 94 written to: chunk-stream0-00093.m4s
[AVIOContext @ 0x7f15af98f040] Statistics: 0 seeks, 1 writeouts
[dash @ 0x7f15af98d040] Representation 1 media segment 94 written to: chunk-stream1-00093.m4s
[dash @ 0x7f15af98d040] Opening 'http://192.168.1.110:32400/video/:/transcode/session/uku8o1pwnmrfa0379bw7po4e/d9eaafb7-7ea8-41bf-9d8a-11c992de5de8/manifest?X-Plex-Http-Pipeline=infinite' for writing
[tcp @ 0x7f15af9849c0] Starting connection attempt to 192.168.1.110 port 32400
[tcp @ 0x7f15af9849c0] Successfully connected to 192.168.1.110 port 32400
```
these are worker logs, it seems to be grabbing the chunks pretty flawlessly but the playback never starts, so I'm confused
```
Forwarding work request to 345e682e-d55c-4e4d-bf03-ce704b1bcf9a|plex-worker-cluster02
Received update for task cc74e9d8-9947-4f57-8b20-1c3d35ed07e5, status: received
Received update for task cc74e9d8-9947-4f57-8b20-1c3d35ed07e5, status: inprogress
```
these are orchestrator logs meanwhile.

```ending request to orchestrator on: http://plex-orchestrator:3500
cwd => "/tmp/Transcode/Transcode/Sessions/plex-transcode-uku8o1pwnmrfa0379bw7po4e-d9eaafb7-7ea8-41bf-9d8a-11c992de5de8"
args => ["-codec:0","hevc","-analyzeduration","20000000","-probesize","20000000","-i","/data/tv/blue.mountain.state.s02e02.the.fingering.webdl-1080p.x265.mkv","-filter_complex","[0:0]scale=w=1920:h=1080[0];[0]format=pix_fmts=yuv420p|nv12[1]","-map","[1]","-codec:0","libx264","-crf:0","16","-maxrate:0","17437k","-bufsize:0","34874k","-r:0","23.975999999999999","-preset:0","veryfast","-x264opts:0","subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none","-force_key_frames:0","expr:gte(t,n_forced*1)","-map","0:1","-metadata:s:1","language=eng","-codec:1","copy","-copypriorss:1","0","-f","dash","-seg_duration","1","-dash_segment_type","mp4","-init_seg_name","init-stream$RepresentationID$.m4s","-media_seg_name","chunk-stream$RepresentationID$-$Number%05d$.m4s","-window_size","5","-delete_removed","false","-skip_to_segment","1","-time_delta","0.0625","-manifest_name","http://192.168.1.110:32400/video/:/transcode/session/uku8o1pwnmrfa0379bw7po4e/d9eaafb7-7ea8-41bf-9d8a-11c992de5de8/manifest?X-Plex-Http-Pipeline=infinite","-avoid_negative_ts","disabled","-map_metadata","-1","-map_chapters","-1","dash","-start_at_zero","-copyts","-vsync","cfr","-y","-nostats","-loglevel","verbose","-loglevel_plex","verbose","-progressurl","http://192.168.1.110:32400/video/:/transcode/session/uku8o1pwnmrfa0379bw7po4e/d9eaafb7-7ea8-41bf-9d8a-11c992de5de8/progress"]
env => {"PUID":"1000","PLEX_ARCH":"amd64","HOSTNAME":"e3c43d97c5c6","LANGUAGE":"en_US.UTF-8","ALLOWED_NETWORKS":"192.168.1.0/24","TRANSCODE_OPERATING_MODE":"remote","ADVERTISE_IP":"\"http://192.168.1.110,http://192.168.1.111\"","ORCHESTRATOR_URL":"http://plex-orchestrator:3500","UMASK":"002","PWD":"/tmp/Transcode/Transcode/Sessions/plex-transcode-uku8o1pwnmrfa0379bw7po4e-d9eaafb7-7ea8-41bf-9d8a-11c992de5de8","PLEX_DOWNLOAD":"https://downloads.plex.tv/plex-media-server-new","PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS":"6","NVIDIA_DRIVER_CAPABILITIES":"compute,video,utility","PMS_IP":"192.168.1.110","PLEX_PASS":"no","TZ":"Europe/Paris","PLEX_MEDIA_SERVER_USER":"abc","HOME":"/root","LANG":"en_US.UTF-8","PGID":"1000","TERM":"xterm","PLEX_MEDIA_SERVER_INFO_VENDOR":"Docker","PLEX_MEDIA_SERVER_HOME":"/usr/lib/plexmediaserver","X_PLEX_TOKEN":"Ng6cCEFzXNxM3HeqzoD_","PLEX_MEDIA_SERVER_INFO_MODEL":"x86_64","SHLVL":"0","LD_LIBRARY_PATH":"/usr/lib","PLEX_MEDIA_SERVER_INFO_PLATFORM_VERSION":"5.4.0-88-generic","LIBVA_DRIVERS_PATH":"/usr/lib/plexmediaserver/lib/dri","PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR":"/config/Library/Application Support","CWD":"/","PATH":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","VERSION":"docker","DEBIAN_FRONTEND":"noninteractive","PLEX_MEDIA_SERVER_INFO_DEVICE":"Docker Container (LinuxServer.io)","FFMPEG_EXTERNAL_LIBS":"/config/Library/Application\\ Support/Plex\\ Media\\ Server/Codecs/be22e26-4019-linux-x86_64/","TRANSCODER_VERBOSE":"1"}
JobPoster connected, announcing
Orchestrator requesting pending work
Sending request to orchestrator on: http://plex-orchestrator:3500
```
pms logs 

ps : I'm so sorry about all of that :(

**Comment by ednxzu** [comment]
```
version: '3.9'

services:
  plex:
    image: ghcr.io/pabloromeo/clusterplex_pms:latest #ghcr.io/linuxserver/plex:latest
    deploy:
      mode: replicated
      replicas: 1
      labels:
          - "traefik.enable=true"
          - "traefik.http.routers.plex.entrypoints=https"
          - "traefik.http.routers.plex.tls=true"
          - "traefik.http.routers.plex.rule=Host(`plextest.ednz.fr`)"
          - "traefik.http.services.plex.loadbalancer.server.port=32400"
    environment:
            #- DOCKER_MODS=ghcr.io/pabloromeo/clusterplex_dockermod:latest
      - VERSION=docker
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Paris
      - ADVERTISE_IP="http://192.168.1.110,http://192.168.1.111"
      - ALLOWED_NETWORKS=192.168.1.0/24
      - PLEX_PASS=no
      - ORCHESTRATOR_URL=http://plex-orchestrator:3500
      - PMS_IP=192.168.1.110
      - TRANSCODE_OPERATING_MODE=remote #(local|remote|both)
      - TRANSCODER_VERBOSE=1   # 1=verbose, 0=silent
    healthcheck:
      test: curl -fsS http://localhost:32400/identity > /dev/null || exit 1
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 30s
    volumes:
      - ./config:/config
      - ./backups:/backups
      - ./tv:/data/tv
      - ./movies:/data/movies
      - ./transcode:/tmp
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 32469:32469
      - 32400:32400
      - 3005:3005
      - 8324:8324
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    networks:
      - traefik-public
      - internal

  plex-orchestrator:
    image: ghcr.io/pabloromeo/clusterplex_orchestrator:latest
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
    environment:
      TZ: Europe/London
      STREAM_SPLITTING: "OFF" # ON | OFF (default)
      LISTENING_PORT: 3500
      WORKER_SELECTION_STRATEGY: "LOAD_CPU" # RR | LOAD_CPU | LOAD_TASKS | LOAD_RANK (default)
    healthcheck:
      test: curl -fsS http://localhost:3500/health > /dev/null || exit 1
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 30s
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3500:3500
    networks:
      - internal

  plex-worker:
    image: ghcr.io/pabloromeo/clusterplex_worker:latest #ghcr.io/linuxserver/plex:latest
    hostname: "plex-worker-{{.Node.Hostname}}"
    deploy:
      mode: global
      update_config:
        order: start-first
    environment:
            #- DOCKER_MODS=ghcr.io/pabloromeo/clusterplex_worker_dockermod:latest
      - VERSION=docker
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - LISTENING_PORT=3501      # used by the healthcheck
      - STAT_CPU_INTERVAL=2000   # interval for reporting worker load metrics
      - ORCHESTRATOR_URL=http://plex-orchestrator:3500
    healthcheck:
      test: curl -fsS http://localhost:3501/health > /dev/null || exit 1
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 240s
    volumes:
      - ./codecs:/codecs # (optional, can be used to share codecs)
      - ./tv:/data/tv
      - ./movies:/data/movies
      - ./transcode:/tmp
      - /etc/localtime:/etc/localtime:ro
    networks:
      - internal

networks:
  internal:
    driver: overlay
  traefik-public:
    external: true
```
here is the updated stack.yml
